name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: nixos
    env:
      PATH: /run/current-system/sw/bin:/usr/bin:/bin
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/cachix-action@v15
        with:
          name: paolino
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix develop --quiet --command just bundle
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist
      - id: deployment
        uses: actions/deploy-pages@v4
